### ISSUE TITLE
 Unesthetic Naming Convention for Extension Method Classes

### ISSUE THREAD

**Issue by HugoRoss** [shaynevanasperen/Quarks#4]
I think the naming convention for the extension method types is not well chosen. The problem with it is, that if it is an extension for an interface, it looks like an interface itself, but should not, because it is a concrete class: e.g. "IEnumerableExtension" has the air of an interface to me.

My suggestion is to flag extension method types with a prefix instead of a suffix, say "ExtIEnumerable" instead of "IEnumerableExtension" which also has the advantage that all extension method types are next to each other when sorted alphabetically.

**Comment by BoeseB** [comment]
I agree, but i would go with "Extends" as prefix so the intention of the class is clearer.
E.g.:  ExtendsIEnumerable

**Comment by HugoRoss** [comment]
Sounds good to me.

**Comment by shaynevanasperen** [comment]
Hello guys. Thanks for your feedback, and I apologise for the delay in replying to this. The naming convention for the extension method types *was* well chosen (I hope). The problem is that it was not documented well enough. The convention is slightly different if the type being extended is an interface, where the only change is to drop the `I` prefix from the extension method's class name. You can see this with the extension method classes in [this folder](https://github.com/shaynevanasperen/Quarks/tree/master/Quarks/IEnumerableExtensions).  This also partly aligns with Microsoft's convention in the `Enumerable` static class in the `System.Linq` namespace, such as for the method `public static IEnumerable<TResult> Repeat<TResult>(TResult element, int count)`. The difference being that I decided to add the `Extension` suffix to the class name.

The Quarks package names for these extensions will still contain the `I` prefix though. For example, the "Quarks.IEnumerableExtensions.Contains" package defines a class named `static partial class EnumerableExtension`. I have now updated the readme documentation to reflect this minor difference. You can see the change in [this commit](https://github.com/shaynevanasperen/Quarks/commit/8e32fdc0d0503a1378f5a705009f4db935348a81)
